CREATE TABLE IF NOT EXISTS `service_readiness_checks` (
  `id` int AUTO_INCREMENT NOT NULL,
  `patientId` int NOT NULL,
  `context` enum('opd_visit','emergency','referral','cross_border','medical_tourist','insurance_claim','pharmacy_dispense') NOT NULL,
  `hospitalId` int,
  `serviceName` varchar(255),
  `score` int NOT NULL,
  `criticalReady` boolean NOT NULL DEFAULT false,
  `requiredMissing` json,
  `recommendedMissing` json,
  `selectedCredentialIds` json,
  `packetPresentationId` varchar(255),
  `shlId` int,
  `status` enum('draft','ready','shared','completed','cancelled') NOT NULL DEFAULT 'draft',
  `metadata` json,
  `createdBy` int,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `service_readiness_checks_id` PRIMARY KEY(`id`),
  KEY `service_readiness_patient_context_idx` (`patientId`, `context`),
  KEY `service_readiness_packet_idx` (`packetPresentationId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `wallet_document_requests` (
  `id` int AUTO_INCREMENT NOT NULL,
  `requestId` varchar(255) NOT NULL,
  `patientId` int NOT NULL,
  `context` enum('opd_visit','emergency','referral','cross_border','medical_tourist','insurance_claim','pharmacy_dispense') NOT NULL,
  `documentType` varchar(100) NOT NULL,
  `documentCategory` varchar(64),
  `sourceType` enum('his','lis','ris','pacs','hospital_app','national_app','partner_portal','payer','patient_upload','personal_health_app','other') NOT NULL DEFAULT 'his',
  `sourceName` varchar(255),
  `targetHospitalId` int,
  `status` enum('draft','pending_consent','requested','imported','needs_review','converted_to_vc','rejected','cancelled') NOT NULL DEFAULT 'requested',
  `requestedBy` int,
  `consentRecordId` int,
  `caseDocumentId` int,
  `credentialRequestId` int,
  `notes` text,
  `metadata` json,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `wallet_document_requests_id` PRIMARY KEY(`id`),
  CONSTRAINT `wallet_document_requests_requestId_unique` UNIQUE(`requestId`),
  KEY `wallet_document_requests_patient_context_idx` (`patientId`, `context`),
  KEY `wallet_document_requests_status_idx` (`status`)
);
