export type SystemRole = "system_admin" | "hospital_admin" | "maker" | "checker" | "doctor" | "nurse" | "integration_engineer" | "patient";

export interface MenuItem {
  id: string;
  label: string;
  labelEn: string;
  icon: string;
  path: string;
  roles: SystemRole[];
  group: string;
  groupLabel: string;
  groupLabelEn: string;
}

export const menuGroups = [
  { id: "service_readiness", label: "ความพร้อมก่อนรับบริการ", labelEn: "Service Readiness" },
  { id: "care_transition", label: "การส่งต่อการรักษา", labelEn: "Care Transition" },
  { id: "verified_documents", label: "เอกสารรับรอง", labelEn: "Verified Documents" },
  { id: "hospital_ops", label: "งานโรงพยาบาล", labelEn: "Hospital Operations" },
  { id: "integration_governance", label: "เชื่อมต่อและกำกับดูแล", labelEn: "Integration & Governance" },
] as const;

export const menuItems: MenuItem[] = [
  {
    id: "dashboard",
    label: "แดชบอร์ด",
    labelEn: "Dashboard",
    icon: "LayoutDashboard",
    path: "/dashboard",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor", "nurse", "integration_engineer", "patient"],
    group: "hospital_ops",
    groupLabel: "งานโรงพยาบาล",
    groupLabelEn: "Hospital Operations",
  },
  {
    id: "executive",
    label: "แดชบอร์ดผู้บริหาร",
    labelEn: "Executive Dashboard",
    icon: "BarChart3",
    path: "/executive",
    roles: ["system_admin", "hospital_admin"],
    group: "hospital_ops",
    groupLabel: "งานโรงพยาบาล",
    groupLabelEn: "Hospital Operations",
  },
  {
    id: "prepare-service",
    label: "เตรียมเข้ารับบริการ",
    labelEn: "Prepare for Service",
    icon: "HeartPulse",
    path: "/prepare-service",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor", "nurse", "integration_engineer", "patient"],
    group: "service_readiness",
    groupLabel: "ความพร้อมก่อนรับบริการ",
    groupLabelEn: "Service Readiness",
  },
  {
    id: "service-verify",
    label: "ตรวจสอบจุดบริการ",
    labelEn: "Service Point Verify",
    icon: "ScanLine",
    path: "/service-verify",
    roles: ["system_admin", "hospital_admin", "doctor", "nurse"],
    group: "service_readiness",
    groupLabel: "ความพร้อมก่อนรับบริการ",
    groupLabelEn: "Service Readiness",
  },
  {
    id: "wallet",
    label: "กระเป๋าสุขภาพ",
    labelEn: "Health Wallet",
    icon: "Wallet",
    path: "/wallet",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor", "nurse", "integration_engineer", "patient"],
    group: "service_readiness",
    groupLabel: "ความพร้อมก่อนรับบริการ",
    groupLabelEn: "Service Readiness",
  },
  {
    id: "consent",
    label: "ประวัติความยินยอม",
    labelEn: "Consent History",
    icon: "ShieldCheck",
    path: "/consent",
    roles: [],
    group: "service_readiness",
    groupLabel: "ความพร้อมก่อนรับบริการ",
    groupLabelEn: "Service Readiness",
  },
  {
    id: "shl",
    label: "ลิงก์แชร์สุขภาพ",
    labelEn: "Smart Share",
    icon: "Link2",
    path: "/shl",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor", "nurse", "integration_engineer", "patient"],
    group: "service_readiness",
    groupLabel: "ความพร้อมก่อนรับบริการ",
    groupLabelEn: "Service Readiness",
  },
  {
    id: "referral",
    label: "ส่งต่อผู้ป่วย",
    labelEn: "Patient Referral",
    icon: "ArrowRightLeft",
    path: "/referral",
    roles: ["system_admin", "hospital_admin", "doctor", "nurse"],
    group: "care_transition",
    groupLabel: "การส่งต่อการรักษา",
    groupLabelEn: "Care Transition",
  },
  {
    id: "cross-border",
    label: "ส่งต่อข้ามเครือข่าย",
    labelEn: "Cross-border Referral",
    icon: "Globe",
    path: "/cross-border",
    roles: ["system_admin", "hospital_admin", "doctor"],
    group: "care_transition",
    groupLabel: "การส่งต่อการรักษา",
    groupLabelEn: "Care Transition",
  },
  {
    id: "international",
    label: "ผู้ป่วยต่างชาติ",
    labelEn: "International Patients",
    icon: "Plane",
    path: "/international",
    roles: ["system_admin", "hospital_admin", "doctor", "nurse"],
    group: "care_transition",
    groupLabel: "การส่งต่อการรักษา",
    groupLabelEn: "Care Transition",
  },
  {
    id: "partner-portal",
    label: "Partner Portal",
    labelEn: "Partner Portal",
    icon: "Handshake",
    path: "/partner-portal",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor", "nurse", "integration_engineer"],
    group: "care_transition",
    groupLabel: "การส่งต่อการรักษา",
    groupLabelEn: "Care Transition",
  },
  {
    id: "issuer",
    label: "ออกเอกสารเข้ากระเป๋า",
    labelEn: "Issue to Wallet",
    icon: "BadgeCheck",
    path: "/issuer",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor"],
    group: "verified_documents",
    groupLabel: "เอกสารรับรอง",
    groupLabelEn: "Verified Documents",
  },
  {
    id: "maker-queue",
    label: "สร้างคำขอ VC (Maker)",
    labelEn: "Create VC Request (Maker)",
    icon: "FilePlus",
    path: "/maker-queue",
    roles: ["system_admin", "hospital_admin", "maker", "doctor", "nurse"],
    group: "verified_documents",
    groupLabel: "เอกสารรับรอง",
    groupLabelEn: "Verified Documents",
  },
  {
    id: "checker-queue",
    label: "ตรวจสอบคำขอ (Checker)",
    labelEn: "Review Requests (Checker)",
    icon: "ClipboardCheck",
    path: "/checker-queue",
    roles: ["system_admin", "hospital_admin", "checker", "doctor"],
    group: "verified_documents",
    groupLabel: "เอกสารรับรอง",
    groupLabelEn: "Verified Documents",
  },
  {
    id: "verifier",
    label: "ตรวจสอบเอกสารรับรอง",
    labelEn: "Verify Credential",
    icon: "ScanLine",
    path: "/verifier",
    roles: ["system_admin", "hospital_admin", "checker", "doctor", "nurse"],
    group: "verified_documents",
    groupLabel: "เอกสารรับรอง",
    groupLabelEn: "Verified Documents",
  },
  {
    id: "trust-registry",
    label: "ทะเบียนความน่าเชื่อถือ",
    labelEn: "Trust Registry",
    icon: "ShieldAlert",
    path: "/trust-registry",
    roles: ["system_admin", "hospital_admin"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "claim-center",
    label: "ศูนย์เคลม",
    labelEn: "Claim Center",
    icon: "Receipt",
    path: "/claim-center",
    roles: ["system_admin", "hospital_admin", "doctor", "nurse"],
    group: "hospital_ops",
    groupLabel: "งานโรงพยาบาล",
    groupLabelEn: "Hospital Operations",
  },
  {
    id: "claim-analytics",
    label: "วิเคราะห์เคลม",
    labelEn: "Claim Analytics",
    icon: "BarChart3",
    path: "/claim-analytics",
    roles: ["system_admin", "hospital_admin"],
    group: "hospital_ops",
    groupLabel: "งานโรงพยาบาล",
    groupLabelEn: "Hospital Operations",
  },
  {
    id: "integration",
    label: "เชื่อมต่อระบบ HIS",
    labelEn: "HIS Integration",
    icon: "Plug",
    path: "/integration",
    roles: ["system_admin", "hospital_admin", "integration_engineer"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "portability",
    label: "Patient Data Portability",
    labelEn: "Portability Layer",
    icon: "FileJson2",
    path: "/portability",
    roles: ["system_admin", "hospital_admin", "maker", "checker", "doctor", "integration_engineer"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "fhir-mapping",
    label: "แผนที่ข้อมูล FHIR",
    labelEn: "FHIR Mapping",
    icon: "GitBranch",
    path: "/fhir-mapping",
    roles: ["system_admin", "hospital_admin", "integration_engineer"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "terminology",
    label: "จับคู่รหัสมาตรฐาน",
    labelEn: "Terminology Mapping",
    icon: "BookOpen",
    path: "/terminology",
    roles: ["system_admin", "hospital_admin", "integration_engineer"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "adapter-sdk",
    label: "Adapter SDK",
    labelEn: "Adapter SDK",
    icon: "Code2",
    path: "/adapter-sdk",
    roles: ["system_admin", "hospital_admin", "integration_engineer"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "patient-identity",
    label: "เชื่อมโยงตัวตน (MPI)",
    labelEn: "Patient Identity (MPI)",
    icon: "Fingerprint",
    path: "/patient-identity",
    roles: ["system_admin", "hospital_admin", "integration_engineer"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "hospitals",
    label: "จัดการเครือข่าย",
    labelEn: "Network Management",
    icon: "Building2",
    path: "/hospitals",
    roles: ["system_admin", "hospital_admin"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "partner-wizard",
    label: "เพิ่มพันธมิตรต่างประเทศ",
    labelEn: "Partner Onboarding",
    icon: "Globe",
    path: "/partner-wizard",
    roles: ["system_admin", "hospital_admin"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "audit",
    label: "บันทึกการเข้าถึง",
    labelEn: "Audit Trail",
    icon: "FileSearch",
    path: "/audit",
    roles: ["system_admin", "hospital_admin"],
    group: "hospital_ops",
    groupLabel: "งานโรงพยาบาล",
    groupLabelEn: "Hospital Operations",
  },
  {
    id: "users",
    label: "จัดการผู้ใช้",
    labelEn: "User Management",
    icon: "Users",
    path: "/users",
    roles: ["system_admin", "hospital_admin"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
  {
    id: "settings",
    label: "ตั้งค่าระบบ",
    labelEn: "Settings",
    icon: "Settings",
    path: "/settings",
    roles: ["system_admin", "hospital_admin"],
    group: "integration_governance",
    groupLabel: "เชื่อมต่อและกำกับดูแล",
    groupLabelEn: "Integration & Governance",
  },
];

export function getMenuForRole(role: SystemRole): MenuItem[] {
  return menuItems.filter(item => item.roles.includes(role));
}

export function getGroupedMenu(role: SystemRole) {
  const items = getMenuForRole(role);
  const grouped: Record<string, MenuItem[]> = {};
  for (const item of items) {
    if (!grouped[item.group]) grouped[item.group] = [];
    grouped[item.group].push(item);
  }
  return menuGroups
    .filter(g => grouped[g.id]?.length)
    .map(g => ({ ...g, items: grouped[g.id]! }));
}
